name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: examples
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true
      
      - name: git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: git commit && git push
        run: |
          git checkout -b gh-pages
          mv examples/*.pdf ./
          find . -type f,l ! -iwholename "./.git/*" ! -iname "*.pdf" -delete
          touch .nojekyll
          git add .
          git commit -m "updated PDFs from commit ${GITHUB_SHA::8}"
          git push -f origin gh-pages
